### ISSUE TITLE
interface conversion: interface {} is nil, not []uint8

### ISSUE THREAD

**Issue by mgale** [weitblick/epub#7]
I am trying to convert the following Hugo site to an ebook, apologies in advance I know nothing about Hugo:
https://github.com/vitessio/website

The site does work locally without modification via:
hugo server --buildDrafts --buildFuture

I then did the following:

- git clone https://github.com/weitblick/epub.git themes/epub
- Replaced config.toml with am exact copy from here your exampleSite/config.toml
- hugo --cleanDestinationDir

Which results in this error:

`Error: Error building site: "/home/michaelgale/workspace/website/content/en/community.md:1:1": interface conversion: interface {} is nil, not []uint8`

Full output below:
`hugo --cleanDestinationDir
Start building sites … 
hugo v0.98.0-165d299cde259c8b801abadc6d3405a229e449f6+extended linux/amd64 BuildDate=2022-04-28T10:23:30Z VendorInfo=gohugoio
ERROR 2022/05/03 11:15:24 [BUG] Got panic:
interface conversion: interface {} is nil, not []uint8
goroutine 108 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/gohugoio/hugo/hugolib.newPageContentOutput.func1.1()
	/root/project/hugo/hugolib/page__per_output.go:99 +0xaa
panic({0x208a660, 0xc00287a3f0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/gohugoio/hugo/markup/goldmark.(*hookedRenderer).renderHeading(0xc000ecd680?, {0x2884e90?, 0xc00330d920?}, {0xc001929000, 0xced, 0xe8c}, {0x2894150?, 0xc000ecc1b0}, 0x0)
	/root/project/hugo/markup/goldmark/render_hooks.go:377 +0x67e
github.com/yuin/goldmark/renderer.(*renderer).Render.func2({0x2894150, 0xc000ecc1b0}, 0x60?)
	/go/pkg/mod/github.com/yuin/goldmark@v1.4.12/renderer/renderer.go:166 +0xc7
github.com/yuin/goldmark/ast.walkHelper({0x2894150, 0xc000ecc1b0}, 0xc003463760)
	/go/pkg/mod/github.com/yuin/goldmark@v1.4.12/ast/ast.go:503 +0xbe
github.com/yuin/goldmark/ast.walkHelper({0x2893cd0, 0xc000ecc120}, 0xc003463760)
	/go/pkg/mod/github.com/yuin/goldmark@v1.4.12/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.Walk(...)
	/go/pkg/mod/github.com/yuin/goldmark@v1.4.12/ast/ast.go:487
github.com/yuin/goldmark/renderer.(*renderer).Render(0xc000098c30?, {0x2871840?, 0xc00330d920?}, {0xc001929000?, 0xced?, 0xe8c?}, {0x2893cd0?, 0xc000ecc120?})
	/go/pkg/mod/github.com/yuin/goldmark@v1.4.12/renderer/renderer.go:161 +0x225
github.com/gohugoio/hugo/markup/goldmark.(*goldmarkConverter).Convert(0xc001377680, {{0xc001929000, 0xced, 0xe8c}, 0x1, 0xc00330d530})
	/root/project/hugo/markup/goldmark/convert.go:195 +0x4d2
github.com/gohugoio/hugo/hugolib.(*pageContentOutput).renderContentWithConverter(0xc00142a540, {0x2879350?, 0xc001377680?}, {0xc001929000?, 0x0?, 0x0?}, 0x0?)
	/root/project/hugo/hugolib/page__per_output.go:580 +0xa3
github.com/gohugoio/hugo/hugolib.(*pageContentOutput).renderContent(0xc00142a540, {0xc001929000, 0xced, 0xe8c}, 0x0?)
	/root/project/hugo/hugolib/page__per_output.go:576 +0x8a
github.com/gohugoio/hugo/hugolib.newPageContentOutput.func1()
	/root/project/hugo/hugolib/page__per_output.go:124 +0x30e
github.com/gohugoio/hugo/hugolib.newPageContentOutput.func2({0x0?, 0x0?})
	/root/project/hugo/hugolib/page__per_output.go:199 +0x1b
github.com/gohugoio/hugo/lazy.(*Init).withTimeout.func1()
	/root/project/hugo/lazy/init.go:188 +0x3c
created by github.com/gohugoio/hugo/lazy.(*Init).withTimeout
	/root/project/hugo/lazy/init.go:187 +0x11e
Error: Error building site: "/home/michaelgale/workspace/website/content/en/community.md:1:1": interface conversion: interface {} is nil, not []uint8
Total in 482 ms
`

**Comment by weitblick** [comment]
> apologies in advance I know nothing about Hugo

I am so sorry, but the epub theme requires advanced knowledge in HUGO ...

It is not so easy to convert an existing HUGO website into an ebook by swapping the theme and customizing config.toml. You need to merge both projects and for that you need to understand exactly how the themes work.

**Comment by mgale** [comment]
That is too bad, I will close this issue request then. Thank you for responding.
